//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public int Languages_ID { get; set; }
        public int Knowledge_ID { get; set; }
        public Nullable<double> Swedish { get; set; }
        public Nullable<double> English { get; set; }
        public double German { get; set; }
        public Nullable<double> Spanish { get; set; }
        public string Other { get; set; }
    
        public virtual Knowledge Knowledge { get; set; }
    }
}
