//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PersonalInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonalInformation()
        {
            this.Customer = new HashSet<Customer>();
            this.Freelancer = new HashSet<Freelancer>();
        }
    
        public int PersonalInformation_ID { get; set; }
        [StringLength(55)]
        [Display(Name = "Förnamn")]
        public string FirstName { get; set; }
        [StringLength(55)]
        [Display(Name = "Efternamn")]
        public string LastName { get; set; }
        [StringLength(255)]
        [Display(Name = "Adress")]
        public string Adress { get; set; }
        [StringLength(55)]
        [Display(Name = "Telefonnummer")]
        public string Telephone { get; set; }
        [StringLength(55)]
        [Display(Name = "Epostadress")]
        public string Email { get; set; }
        public string UserGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Freelancer> Freelancer { get; set; }
    }
}
